### ISSUE TITLE
 problem with command

### ISSUE THREAD

**Issue by llronaldoll** [HBIDamian/TimeCommander#3]
when I use the selector @a command, I get the message to run the ingame command!

**Comment by Ad5001** [comment]
Hello, I'm the author of PlayerSelectors (the plugin which allows you to use selectors). The issue you're stating here does not come either from this plugin nor PlayerSelectors. 
The issue likely comes from the plugin which the command you're trying to execute comes from, which requires the command to be sent as a player. You should try to use this command with a command such as "/as" from the Essentials plugin.
For this part, you should contact the author of this other plugin, as this issue is neither related to PlayerSelectors nor TimeCommander.
